package com.aes.common.Trefle.Models

class RangeDTO (
    var atmospheric_humidity: String? = null,
    var average_height_cm: String? = null,
    var days_to_harvest: String? = null,
    var frost_free_days_minimum: String? = null,
    var ground_humidity: String? = null,
    var images_count: String? = null,
    var light: String? = null,
    var maximum_height_cm: String? = null,
    var maximum_precipitation_mm: String? = null,
    var maximum_temperature_deg_c: String? = null,
    var maximum_temperature_deg_f: String? = null,
    var minimum_precipitation_mm: String? = null,
    var minimum_root_depth_cm: String? = null,
    var minimum_temperature_deg_c: String? = null,
    var minimum_temperature_deg_f: String? = null,
    var ph_maximum: String? = null,
    var ph_minimum: String? = null,
    var planting_days_to_harvest: String? = null,
    var planting_row_spacing_cm: String? = null,
    var planting_spread_cm: String? = null,
    var soil_nutriments: String? = null,
    var soil_salinity: String? = null,
    var soil_texture: String? = null,
    var sources_count: String? = null,
    var synonyms_count: String? = null,
    var toxicity: String? = null,
    var year: String? = null
)